CREATE TABLE SEG_USUARIO_AREA (
  ID_USUARIO NUMBER NOT NULL,
  ID_AREA NUMBER NOT NULL,
  CONSTRAINT PK_SEG_USUARIO_AREA PRIMARY KEY (ID_USUARIO, ID_AREA),
  CONSTRAINT FK_SEG_USUARIO_AREA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES SEG_USUARIO (ID_USUARIO),
  CONSTRAINT FK_SEG_USUARIO_AREA_AREA FOREIGN KEY (ID_AREA) REFERENCES SEG_AREA (ID_AREA)
);

CREATE TABLE SEG_USUARIO_REGION (
  ID_USUARIO NUMBER NOT NULL,
  ID_REGION NUMBER NOT NULL,
  CONSTRAINT PK_SEG_USUARIO_REGION PRIMARY KEY (ID_USUARIO, ID_REGION),
  CONSTRAINT FK_SEG_USUARIO_REGION_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES SEG_USUARIO (ID_USUARIO),
  CONSTRAINT FK_SEG_USUARIO_REGION_REGION FOREIGN KEY (ID_REGION) REFERENCES SEG_REGION (ID_REGION)
);

INSERT INTO SEG_USUARIO_AREA (ID_USUARIO, ID_AREA)
SELECT ID_USUARIO, ID_AREA
FROM SEG_USUARIO
WHERE ROL = 'Inspector' AND ID_AREA IS NOT NULL;

INSERT INTO SEG_USUARIO_REGION (ID_USUARIO, ID_REGION)
SELECT ID_USUARIO, ID_REGION
FROM SEG_USUARIO
WHERE ROL = 'Inspector' AND ID_REGION IS NOT NULL AND ID_AREA IS NULL;

COMMIT;