-- ============================================================
-- SGGDIS - Script de creacion de base de datos (Oracle)
-- Catalogo completo (Guia, Tipos de establecimiento, Secciones, Items)
-- Alcance: catalogo completo de la Guia de Inspeccion para Servicios de
-- Alimentacion al Publico (tomado del Excel oficial) + lo minimo para
-- pintar el formulario en el frontend segun tipo de establecimiento.
--
-- NOTA: por ahora NO se incluyen las tablas transaccionales de guardado
-- (INS_INSPECCION, INS_RESPUESTA). Esto queda para un sprint posterior.
--
-- Secciones: A, B1, B2, B3, C1, C2, D, E, F, G, H (11 en total).
-- B1/B2/B3 y C1/C2 son subsecciones aplanadas a nivel de seccion, igual
-- que A, D, E, F, G, H (mismo estilo, mismo ID_SECCION por codigo).
-- ============================================================

-- ============================================
-- 1. Catalogo: Guia (el reglamento en si)
-- ============================================

CREATE TABLE INS_GUIA (
  ID_GUIA     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  NOMBRE      VARCHAR2(150) NOT NULL,
  DESCRIPCION VARCHAR2(300),
  CATEGORIA   VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_GUIA PRIMARY KEY (ID_GUIA)
);

-- ============================================
-- 2. Catalogo: Tipos de establecimiento (dato real, Excel)
-- ============================================

CREATE TABLE INS_TIPO_ESTABLECIMIENTO (
  ID_TIPO_ESTABLECIMIENTO  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  ID_GUIA                  NUMBER NOT NULL,
  NOMBRE                   VARCHAR2(100) NOT NULL,
  PUNTAJE_MAXIMO           NUMBER NOT NULL,
  ORDEN                    NUMBER NOT NULL,
  CONSTRAINT PK_TIPO_ESTABLECIMIENTO PRIMARY KEY (ID_TIPO_ESTABLECIMIENTO),
  CONSTRAINT FK_TIPOESTABL_GUIA FOREIGN KEY (ID_GUIA) REFERENCES INS_GUIA (ID_GUIA)
);

-- ============================================
-- 3. Catalogo: Secciones de la guia
--    (incluye A, B1, B2, B3, C1, C2, D, E, F, G, H - 11 en total)
-- ============================================

CREATE TABLE INS_SECCION (
  ID_SECCION  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  ID_GUIA     NUMBER NOT NULL,
  CODIGO      VARCHAR2(5) NOT NULL,
  NOMBRE      VARCHAR2(150) NOT NULL,
  ORDEN       NUMBER NOT NULL,
  CONSTRAINT PK_SECCION PRIMARY KEY (ID_SECCION),
  CONSTRAINT FK_SECCION_GUIA FOREIGN KEY (ID_GUIA) REFERENCES INS_GUIA (ID_GUIA)
);

-- ============================================
-- 4. Puente: que secciones aplican a cada tipo de establecimiento
-- ============================================

CREATE TABLE INS_TIPO_SECCION (
  ID_TIPO_ESTABLECIMIENTO  NUMBER NOT NULL,
  ID_SECCION               NUMBER NOT NULL,
  CONSTRAINT PK_TIPO_SECCION PRIMARY KEY (ID_TIPO_ESTABLECIMIENTO, ID_SECCION),
  CONSTRAINT FK_TIPOSECCION_TIPO FOREIGN KEY (ID_TIPO_ESTABLECIMIENTO) REFERENCES INS_TIPO_ESTABLECIMIENTO (ID_TIPO_ESTABLECIMIENTO),
  CONSTRAINT FK_TIPOSECCION_SECCION FOREIGN KEY (ID_SECCION) REFERENCES INS_SECCION (ID_SECCION)
);

-- ============================================
-- 5. Catalogo: Items de cada seccion
--    NOTA: ARTICULO se amplio a VARCHAR2(100) porque hay valores reales
--    del Excel que superan los 60 caracteres.
-- ============================================

CREATE TABLE INS_ITEM (
  ID_ITEM             NUMBER GENERATED BY DEFAULT AS IDENTITY,
  ID_SECCION          NUMBER NOT NULL,
  ARTICULO            VARCHAR2(100) NOT NULL,
  DESCRIPCION         VARCHAR2(400) NOT NULL,
  PUNTAJE             NUMBER NOT NULL,
  ES_CRITICO          CHAR(1) DEFAULT 'N' NOT NULL,
  PERMITE_NO_APLICA   CHAR(1) DEFAULT 'S' NOT NULL,
  ORDEN               NUMBER NOT NULL,
  CONSTRAINT PK_ITEM PRIMARY KEY (ID_ITEM),
  CONSTRAINT FK_ITEM_SECCION FOREIGN KEY (ID_SECCION) REFERENCES INS_SECCION (ID_SECCION),
  CONSTRAINT CK_ITEM_CRITICO CHECK (ES_CRITICO IN ('S','N')),
  CONSTRAINT CK_ITEM_NOAPLICA CHECK (PERMITE_NO_APLICA IN ('S','N'))
);

-- ============================================
-- 6. Datos: Guia
-- ============================================

INSERT INTO INS_GUIA (NOMBRE, DESCRIPCION, CATEGORIA) VALUES
('Guia de Inspeccion para Servicios de Alimentacion al Publico',
 'Reglamento de Servicio de Alimentacion al Publico N 37308-S, Acuerdo 1803',
 'Servicios de Alimentacion al Publico');

-- ============================================
-- 7. Datos: Tipos de establecimiento (reales, Excel)
-- ============================================

INSERT INTO INS_TIPO_ESTABLECIMIENTO (ID_GUIA, NOMBRE, PUNTAJE_MAXIMO, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'), 'Soda, Restaurante o Bar con servicio Express', 210, 1);
INSERT INTO INS_TIPO_ESTABLECIMIENTO (ID_GUIA, NOMBRE, PUNTAJE_MAXIMO, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'), 'Soda, Restaurante o Bar sin servicio Express', 199, 2);
INSERT INTO INS_TIPO_ESTABLECIMIENTO (ID_GUIA, NOMBRE, PUNTAJE_MAXIMO, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'), 'Servicios de Catering', 171, 3);
INSERT INTO INS_TIPO_ESTABLECIMIENTO (ID_GUIA, NOMBRE, PUNTAJE_MAXIMO, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'), 'Servicio Express', 180, 4);
INSERT INTO INS_TIPO_ESTABLECIMIENTO (ID_GUIA, NOMBRE, PUNTAJE_MAXIMO, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'), 'Ventana', 177, 5);

-- ============================================
-- 8. Datos: Secciones A, B1, B2, B3, C1, C2, D, E, F, G, H
-- ============================================

INSERT INTO INS_SECCION (ID_GUIA, CODIGO, NOMBRE, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'),
 'A', 'Condiciones Fisicas y Sanitarias Generales de las Instalaciones', 1);
INSERT INTO INS_SECCION (ID_GUIA, CODIGO, NOMBRE, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'),
 'B1', 'Area de Preparacion de Alimentos (Cocina) - Condiciones Fisicas y Sanitarias', 2);
INSERT INTO INS_SECCION (ID_GUIA, CODIGO, NOMBRE, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'),
 'B2', 'Area de Preparacion de Alimentos (Cocina) - Equipo y Utensilios', 3);
INSERT INTO INS_SECCION (ID_GUIA, CODIGO, NOMBRE, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'),
 'B3', 'Area de Preparacion de Alimentos (Cocina) - Operaciones de Preparacion de los Alimentos', 4);
INSERT INTO INS_SECCION (ID_GUIA, CODIGO, NOMBRE, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'),
 'C1', 'Del Almacenamiento de Alimentos - Condiciones Fisicas y Sanitarias', 5);
INSERT INTO INS_SECCION (ID_GUIA, CODIGO, NOMBRE, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'),
 'C2', 'Del Almacenamiento de Alimentos - Condiciones de Almacenamiento', 6);
INSERT INTO INS_SECCION (ID_GUIA, CODIGO, NOMBRE, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'),
 'D', 'Medidas de Saneamiento', 7);
INSERT INTO INS_SECCION (ID_GUIA, CODIGO, NOMBRE, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'),
 'E', 'Salud e Higiene del Personal', 8);
INSERT INTO INS_SECCION (ID_GUIA, CODIGO, NOMBRE, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'),
 'F', 'Area de Consumo (Comedor)', 9);
INSERT INTO INS_SECCION (ID_GUIA, CODIGO, NOMBRE, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'),
 'G', 'Servicio a Domicilio', 10);
INSERT INTO INS_SECCION (ID_GUIA, CODIGO, NOMBRE, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'),
 'H', 'Servicio de Catering', 11);

-- ============================================
-- 9. Datos: que secciones usa cada tipo de establecimiento
-- ============================================

INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar con servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar con servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar con servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar con servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar con servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar con servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar con servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'E')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar con servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar con servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'G')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar con servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar sin servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar sin servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar sin servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar sin servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar sin servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar sin servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar sin servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'E')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar sin servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Soda, Restaurante o Bar sin servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicios de Catering';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicios de Catering';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicios de Catering';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicios de Catering';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicios de Catering';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicios de Catering';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicios de Catering';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'E')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicios de Catering';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'H')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicios de Catering';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'E')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'G')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Servicio Express';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Ventana';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Ventana';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Ventana';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Ventana';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Ventana';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Ventana';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Ventana';
INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'E')
FROM INS_TIPO_ESTABLECIMIENTO WHERE NOMBRE = 'Ventana';

-- ============================================
-- 10. Datos: los 156 items reales, ya repartidos en las 11 secciones
--     (A=22 B1=23 B2=18 B3=16 C1=13 C2=11 D=20 E=8 F=16 G=3 H=6)
-- ============================================

-- Seccion A
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Ubicacion - Art. 5', 'Distancia mayor o igual a 3m de expendios y bodegas de agroquimicos que no realizan mezclas y mayor o igual a 10m de aquellas que realizan mezclas.', 1, 'N', 1);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Ubicacion - Art. 5', 'Limpios, libres de basura o equipo en desuso', 1, 'N', 2);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Alrededores - Art. 6', 'Libres de aguas estancadas', 1, 'N', 3);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Alrededores - Art. 6', 'Zonas verdes y ornamentales recortadas y libres de maleza', 1, 'N', 4);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Alrededores - Art. 6', 'Se observan equipos o materiales en desuso que puedan constituirse en atraccion y refugio para insectos y roedores', 1, 'N', 5);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Alrededores - Art. 6', 'Mantenimiento adecuado de los conductos o canales exteriores que drenan las aguas, para evitar su estancamiento.', 1, 'N', 6);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Edificaciones - Art. 7', 'La edificacion se encuentra en buenas condiciones fisicas e higienicas.', 1, 'N', 7);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Edificaciones - Art. 7', 'Cumple con las condiciones de acceso reguladas por la Ley 7600', 1, 'N', 8);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Edificaciones - Art. 7', 'Esta independiente de viviendas u otras actividades de naturaleza distinta', 1, 'N', 9);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Distribucion de las Areas - Art. 8 y 9', 'Segun corresponda, cuenta con las areas claramente definidas de: almacenamiento y conservacion, Preparacion, Consumo, Servicios sanitarios', 1, 'N', 10);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Distribucion de las Areas - Art. 8 y 9', 'Las dimensiones permiten el desarrollo adecuado de cada actividad', 1, 'N', 11);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones de Gas - Art. 11', 'Las tuberias o mangueras de gas se encuentran en buenas condiciones de funcionamiento (sin fugas)', 2, 'N', 12);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones de Gas - Art. 11', 'Los cilindros se encuentran en buenas condiciones fisicas y sus llaves de salida operan correctamente', 2, 'N', 13);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones de Gas - Art. 11', 'Los cilindros se encuentran en un area ventilada, segura y debidamente protegida, fuera del area preparacion de alimentos.', 2, 'N', 14);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones de Gas - Art. 11', 'Cuentan con una bitacora donde se anota el mantenimiento preventivo y correctivo de las instalaciones de gas.', 2, 'N', 15);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Abastecimiento de Agua Potable - Art. 10', 'Disposicion de agua potable siempre', 3, 'S', 16);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Abastecimiento de Agua Potable - Art. 10', 'Agua suficiente para ejecutar todas las operaciones en el establecimiento', 3, 'S', 17);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Abastecimiento de Agua Potable - Art. 10', 'Existe un procedimiento escrito para la higienizacion de tanques de almacenamiento cuando cuenten con estos.', 2, 'S', 18);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones Electricas - Art. 12', 'El cableado electrico, tomacorrientes, interruptores y enchufes se mantiene en buenas condiciones de funcionamiento.', 2, 'N', 19);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones Electricas - Art. 12', 'Cuenta con caja de Brecker en buen estado de funcionamiento', 1, 'N', 20);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones Electricas - Art. 12', 'El cableado electrico se encuentra entubado', 1, 'N', 21);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones Electricas - Art. 12', 'Tomacorrientes e interruptores se encuentran anclados.', 1, 'N', 22);

-- Seccion B1
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Flujo - Art. 18', 'El proceso de preparacion de alimentos permite realizarlo de forma secuencial para evitar la contaminacion cruzada.', 2, 'N', 1);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Flujo - Art. 18', 'El area de cocina cuenta con zona de preparacion previa, zona de preparacion intermedia y zona de preparacion final o se divide el trabajo en etapas.', 1, 'N', 2);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Piso - Art. 16', 'Sin fracturas, fisuras o irregularidades en su superficie o uniones', 1, 'N', 3);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Piso - Art. 16', 'Deben estar construidos de materiales que faciliten su limpieza y desinfeccion, impermeables, antideslizantes, resistentes y faciles de limpiar.', 1, 'N', 4);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Piso - Art. 16', 'Deben mantenerse limpios y desinfectados, libres de grasa y sin acumulaciones de agua.', 1, 'N', 5);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Piso - Art. 16', 'Los desagues funcionan eficientemente para evacuar los fluidos.', 1, 'N', 6);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Paredes - Art. 13', 'Deben ser de material impermeable, lisas, faciles de lavar y desinfectar, de color claro y sin grietas', 1, 'N', 7);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Paredes - Art. 13', 'Deben estar en buen estado de conservacion e higiene', 1, 'N', 8);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Paredes - Art. 13', 'Los angulos entre las paredes y pisos son concavos y de facil limpieza y desinfeccion.', 1, 'N', 9);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Cielo Raso - Art. 14', 'Debe ser de construccion solida, tener un diseno que impida la acumulacion de suciedad', 1, 'N', 10);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Cielo Raso - Art. 14', 'Estar construidos de materiales lisos y resistentes a las operaciones de limpieza', 1, 'N', 11);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Cielo Raso - Art. 14', 'La altura minima ente el cielo raso y piso es de 2.50m.', 1, 'N', 12);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Ventanas - Art. 19', 'Estan provistas de proteccion contra insectos u otros animales.', 1, 'N', 13);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Ventanas - Art. 19', 'El sistema de proteccion se desmonta con facilidad para su limpieza y mantenimiento', 1, 'N', 14);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Ventanas - Art. 19', 'Se mantienen limpias', 1, 'N', 15);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Puertas - Art. 20', 'Son de material liso e impermeable y ajustadas a sus marcos', 1, 'N', 16);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Puertas - Art. 20', 'Cuentan con cierre automatico o el sistema de vaiven (cuando aplique)', 1, 'N', 17);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Iluminacion - Art. 21', 'La intensidad de la iluminacion alcanza los 220 lux.', 1, 'N', 18);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Iluminacion - Art. 21', 'Altera los colores de los alimentos', 1, 'N', 19);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Iluminacion - Art. 21', 'Las fuentes luminicas se encuentran con protectores.', 1, 'N', 20);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Ventilacion - Art. 22', 'Cuenta con sistema de ventilacion natural o artificial funcionando adecuadamente.', 1, 'N', 21);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Ventilacion - Art. 22', 'Hay calor excesivo y condensacion de vapores en la cocina', 1, 'N', 22);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B1'), 'Equipos coccion - Art. 17', 'Deben contar con campana extractora con capacidad suficiente para eliminar eficazmente vapores generados', 1, 'N', 23);

-- Seccion B2
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Caracteristicas del Equipo - Art. 23', 'Los equipos y utensilios que estan en contacto directo con los alimentos, son de facil limpieza y desinfeccion', 1, 'N', 24);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Caracteristicas del Equipo - Art. 23', 'Son resistentes a la corrosion y no transmiten sustancias toxicas, olores ni sabores a los alimentos.', 1, 'N', 25);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Caracteristicas del Equipo - Art. 23', 'Se utilizan utensilios de madera o con mangos de madera', 1, 'N', 26);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Tablas de picar - Art. 24', 'Las tablas de picar son de material impermeable, superficie lisa y se mantienen en buen estado de conservacion e higiene', 1, 'N', 27);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Tablas de picar - Art. 24', 'Las tablas deben estar identificados segun su uso, considerando la naturaleza del producto: para carnes crudas, (pollo, bovino y pescado), vegetales y frutas crudas y para alimentos cocidos.', 2, 'N', 28);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Campanas extractoras - Art. 25', 'La campana y ductos de extraccion deben estar ubicados de manera que permitan una adecuada extraccion.', 2, 'N', 29);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Campanas extractoras - Art. 25', 'El Sistema de extraccion cubre la zona destinada a coccion o fritura', 2, 'N', 30);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Campanas extractoras - Art. 25', 'Se mantienen limpias y en buen estado de mantenimiento.', 1, 'N', 31);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Fregaderos o pilas - Art. 26', 'El fregadero se encuentran en buen estado de conservacion, limpieza e higiene', 1, 'N', 32);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Fregaderos o pilas - Art. 26', 'Son de acero inoxidable u otro material resistente y liso', 1, 'N', 33);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Fregaderos o pilas - Art. 26', 'Su capacidad es acorde con el volumen del servicio.', 1, 'N', 34);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Almacenamiento de equipo y utensilios - Art. 27', 'La vajilla, copas y vasos se guardan boca abajo sobre una superficie limpia, seca y protegida de contaminantes y a mas de 30 cm sobre el piso.', 1, 'N', 35);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Almacenamiento de equipo y utensilios - Art. 27', 'Los equipos que no estan siendo utilizados se mantienen cubiertos', 1, 'N', 36);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Almacenamiento de equipo y utensilios - Art. 27', 'Los equipos y utensilios se encuentran alejados de desagues y de recipientes de desechos.', 1, 'N', 37);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Manteleria - Art. 28', 'La manteleria se mantiene en buen estado y limpia', 1, 'N', 38);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Manteleria - Art. 28', 'La manteleria se conserva en un lugar exclusivo pares este uso, libre de polvo y humedad.', 1, 'N', 39);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Manteleria - Art. 28', 'Las servilletas de tela se reemplazan para cada cliente', 1, 'N', 40);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B2'), 'Manteleria - Art. 28', 'Los individuales de plastico u otro material se limpian y desinfectan despues de cada uso', 1, 'N', 41);

-- Seccion B3
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Lavado - Art. 29', 'A las hortalizas, verduras y frutas sin procesar, antes de utilizarlas aplican el procedimiento de lavado y desinfeccion.', 3, 'N', 42);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Descongelado - Art. 30', 'El personal responsable de la preparacion de los alimentos describe correctamente el procedimiento de descongelacion de carnes senalado en el reglamento.', 2, 'N', 43);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Coccion - Art. 31', 'El personal responsable de la preparacion de alimentos cuenta con termometros para verificar las temperaturas de cocimiento establecidas en el reglamento', 1, 'N', 44);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Grasas y Aceites - Art. 32', 'El aceite se observa libre de particulas', 1, 'N', 45);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Grasas y Aceites - Art. 32', 'La filtracion de los aceites, para eliminar particulas solidas se realiza al menos unas vez al dia.', 1, 'N', 46);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Grasas y Aceites - Art. 32', 'Depositan el aceite filtrado a temperatura ambiente en un recipiente tapado.', 1, 'N', 47);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Grasas y Aceites - Art. 32', 'Aplican el procedimiento de fritura establecido en las buenas practicas de manejo de aceites y grasas (anexo 1)', 1, 'N', 48);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Recalentamiento de comidas - Art. 34', 'Los alimentos recalentados se llevan hasta la temperatura de 74 C en el centro por 15 segundos y se mantienen a 60C cuando no se sirven de inmediato', 2, 'N', 49);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Recalentamiento de comidas - Art. 34', 'Los alimentos recalentados que no se consumen el mismo dia son descartados', 2, 'N', 50);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Conservacion de alimentos preelaborados - Art. 33', 'Los alimentos preelaborados y cocinados se conservan tapados, rotulados y en refrigeracion.', 2, 'N', 51);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Conservacion de alimentos preelaborados - Art. 33', 'Los ingredientes crudos o cocidos y embutidos deben mantenerse rotulados y en refrigeracion. El tiempo de conservacion no debe alterar sus caracteristicas organolepticas.', 2, 'N', 52);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Conservacion de alimentos preelaborados - Art. 33', 'Los productos a base de leche y huevo crudo se mantienen en refrigeracion', 1, 'N', 53);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Contaminacion cruzada - Art. 35', 'Los alimentos crudos se almacenan en los equipos de refrigeracion en recipientes de material higienico resistente y tapados o bolsas plasticas y se colocan separados de los cocidos', 2, 'N', 54);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Contaminacion cruzada - Art. 35', 'Las mesas de trabajo se lavan y desinfectan despues de utilizarse con alimentos crudos.', 2, 'N', 55);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Contaminacion cruzada - Art. 35', 'El personal se lava y desinfecta las manos despues de manipular alimentos crudos, para entrar en contacto con alimentos preparados.', 2, 'N', 56);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'B3'), 'Contaminacion cruzada - Art. 35', 'Los utensilios como cuchillos y cucharones se encuentran identificados segun su uso en productos crudos y cocidos', 2, 'N', 57);

-- Seccion C1
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1'), 'Lugar de almacenamiento - Art. 36', 'Se cuenta con un lugar o espacio exclusivo para almacenar productos no perecederos', 1, 'N', 1);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1'), 'Lugar de almacenamiento - Art. 36', 'Se cuenta con camara de refrigeracion o congelacion para almacenar productos perecederos segun corresponda.', 1, 'N', 2);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1'), 'Pisos - Art. 39', 'Construidos de materiales impermeables, antideslizantes, resistentes, faciles de limpiar y desinfectar, mantenerse en buen estado de conservacion e higiene.', 1, 'N', 3);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1'), 'Pisos - Art. 39', 'Sin fracturas, fisuras, grietas ni irregularidades en su superficie o uniones.', 1, 'N', 4);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1'), 'Pisos - Art. 39', 'Deben mantenerse limpios y desinfectados', 1, 'N', 5);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1'), 'Paredes - Art. 37', 'Deben ser de material impermeable, lisas, faciles de lavar y desinfectar y de color claro', 1, 'N', 6);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1'), 'Paredes - Art. 37', 'Deben estar en buen estado de mantenimiento e higiene', 1, 'N', 7);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1'), 'Paredes - Art. 37', 'Los angulos entre pisos y paredes son concavos de facil limpieza y desinfeccion', 1, 'N', 8);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1'), 'Cielo Raso - Art. 38', 'Debe ser de construccion solida y su diseno y acabado debe impedir la acumulacion de suciedad.', 1, 'N', 9);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1'), 'Cielo Raso - Art. 38', 'Los materiales utilizados deben ser lisos y resistentes a las operaciones de limpieza', 1, 'N', 10);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1'), 'Puertas - Art. 40', 'Es de superficie lisa e impermeable y esta ajustada completamente a sus marcos.', 1, 'N', 11);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1'), 'Iluminacion - Art. 41', 'La iluminacion es suficiente para la realizacion de las actividades.', 1, 'N', 12);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C1'), 'Iluminacion - Art. 41', 'Las fuentes luminicas se encuentran con protectores.', 1, 'N', 13);

-- Seccion C2
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2'), 'Productos no Perecederos - Art. 42', 'El lugar se encuentra limpio, seco y ventilado', 1, 'N', 14);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2'), 'Productos no Perecederos - Art. 42', 'Protegido del ingreso de posibles plagas', 2, 'N', 15);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2'), 'Productos no Perecederos - Art. 42', 'Envases tapados e identificados y no estar en contacto con el piso', 1, 'N', 16);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2'), 'Productos no Perecederos - Art. 42', 'Existe control documental en la rotacion de los productos', 1, 'N', 17);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2'), 'Productos no Perecederos - Art. 42', 'El producto debe estar sobre estantes o tarimas, separados del piso 0,15 m.', 1, 'N', 18);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2'), 'Productos perecederos - Art. 43 y equipos de refrigeracion y congelacion Art. 44', 'Almacenamiento de alimentos separados de acuerdo a su naturaleza y debidamente identificados', 2, 'N', 19);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2'), 'Productos perecederos - Art. 43 y equipos de refrigeracion y congelacion Art. 44', 'Alimentos refrigerados a una temperatura igual o menor a 5C', 3, 'N', 20);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2'), 'Productos perecederos - Art. 43 y equipos de refrigeracion y congelacion Art. 44', 'Alimentos congelados de -12C a -18C', 2, 'N', 21);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2'), 'Productos perecederos - Art. 43 y equipos de refrigeracion y congelacion Art. 44', 'El equipo de refrigeracion no sobrepasa su capacidad', 2, 'N', 22);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2'), 'Productos perecederos - Art. 43 y equipos de refrigeracion y congelacion Art. 44', 'Carnes colocadas en recipientes o bolsas plasticas', 2, 'N', 23);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'C2'), 'Productos perecederos - Art. 43 y equipos de refrigeracion y congelacion Art. 44', 'Los alimentos estan colocados separados de manera que permita la circulacion de aire frio', 1, 'N', 24);

-- Seccion D
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Programa de higiene y desinfeccion - Art. 60', 'El establecimiento cuenta con un programa documentado de higiene y desinfeccion que incluye los procedimientos de limpieza y desinfeccion', 2, 'N', 1);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Programa de higiene y desinfeccion - Art. 60', 'Se tiene evidencia de la implementacion del programa de limpieza y desinfeccion', 2, 'N', 2);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Programa de higiene y desinfeccion - Art. 60', 'Los productos de limpieza estan autorizados e identificados y correctamente almacenados', 1, 'N', 3);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Plagas y animales - Art. 61', 'En caso de requerir aplicar plaguicidas el personal que realiza esta labor esta capacitado, o si esta tarea es hecha por una empresa externa esta autorizada por le MS', 1, 'N', 4);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Plagas y animales - Art. 61', 'Se lleva un registro de los resultados de la aplicacion del plan de control de plagas', 1, 'N', 5);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Plagas y animales - Art. 61', 'Los plaguicidas utilizados estan autorizados por la autoridad competente.', 1, 'N', 6);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Plagas y animales - Art. 61', 'Se toman las debidas previsiones para evitar el ingreso de animales domesticos no permitidos', 1, 'N', 7);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Plagas y animales - Art. 61', 'Los plaguicidas se mantienen cerrados, identificados y fuera del area de preparacion de alimentos', 1, 'N', 8);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Servicios sanitarios - Art. 62', 'Cuenta con los elementos indispensables para su correcto funcionamiento (jabon, toallas desechables o secador automatico de aire fuera del recinto del servicio sanitario, papel higienico, lavamanos, recipientes para eliminacion papeles)', 2, 'N', 9);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Servicios sanitarios - Art. 62', 'Su ubicacion no comunica directamente con el area de preparacion de alimentos y cuenta con ventilacion al exterior.', 1, 'N', 10);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Servicios sanitarios - Art. 62', 'Su diseno cumple con lo establecido en la ley 7.600', 1, 'N', 11);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Servicios sanitarios - Art. 62', 'Recintos separados para hombres y mujeres', 1, 'N', 12);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Servicios sanitarios - Art. 62', 'Cumple con la relacion de n de loza sanitaria vrs. N de usuarios', 1, 'N', 13);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'Servicios sanitarios - Art. 62', 'Operan correctamente, se mantienen en buen estado de conservacion e higiene', 2, 'N', 14);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'De los residuos solidos y liquidos - Art. 63', 'Cuenta con plan documentado de manejo de residuos y lo tiene implementado', 2, 'N', 15);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'De los residuos solidos y liquidos - Art. 63', 'Los recipientes destinados a los residuos solidos y sustancias no comestibles estan bien ubicados y se encuentran identificados, limpios y estan construidos de material impermeable', 2, 'N', 16);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'De los residuos solidos y liquidos - Art. 63', 'Se dispone correctamente de los residuos solidos', 1, 'N', 17);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'De los residuos solidos y liquidos - Art. 63', 'Los residuos liquidos se conducen correctamente hacia el sistema de tratamiento o al alcantarillado sanitario, los conductos estan protegidos por rejillas para impedir el ingreso de roedores.', 2, 'N', 18);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'De los residuos solidos y liquidos - Art. 63', 'Se cuenta con trampas de grasas y aceites, y se mantienen en buen estado de funcionamiento e higiene.', 2, 'N', 19);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'D'), 'De los residuos solidos y liquidos - Art. 63', 'Se destina un area aislada y protegida contra plagas para el almacenamiento temporal de recipientes con residuos solidos y se encuentra en buen estado de conservacion e higiene.', 1, 'N', 20);

-- Seccion E
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'E'), 'Art. 4 carne manipulador', 'El personal cuenta con el carne de manipulador de alimentos vigente', 1, 'N', 1);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'E'), 'Salud del personal - Art. 57', 'Se observa al personal libre de lesiones externas como heridas abiertas o infectadas, infecciones cutaneas o llagas', 2, 'N', 2);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'E'), 'Salud del personal - Art. 57', 'El propietario o administrador toma medidas para evitar que el personal enfermo trabaje en zonas de manipulacion de alimentos.', 3, 'N', 3);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'E'), 'Higiene y habitos del personal - Art. 58', 'Los empleados mantienen las unas limpias, recortadas, sin esmalte, no utilizan maquillaje y no portan joyas durante las horas laborales y se observan buenos habitos de higiene. (En su area de trabajo: no comen, no fuman, no mascan chicle entre otros). Esto aplica para el area de preparacion de alimentos.', 2, 'N', 4);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'E'), 'Higiene y habitos del personal - Art. 58', 'El personal encargado de caja que manipula dinero no debe participar en actividades relacionadas con la manipulacion de alimentos durante el tiempo que realiza esta funcion.', 1, 'N', 5);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'E'), 'Higiene y habitos del personal - Art. 58', 'Se aplica correctamente el procedimiento establecido para el lavado de manos', 2, 'N', 6);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'E'), 'Vestimenta - Art. 59', 'El personal destacado en el area de preparacion de alimentos lleva ropa de trabajo limpia, cobertor de cabello, calzado cerrado de material no absorbente.', 2, 'N', 7);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'E'), 'Vestimenta - Art. 59', 'La ropa del personal en general se encuentra limpia y en buen estado de conservacion', 1, 'N', 8);

-- Seccion F
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Materiales de construccion y distribucion - Art. 45 y 46', 'El espacio permite la circulacion adecuada de los usuarios y se mantiene en buenas condiciones de limpieza', 1, 'N', 1);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Materiales de construccion y distribucion - Art. 45 y 46', 'Mobiliario de material resistente, de facil limpieza', 1, 'N', 2);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Materiales de construccion y distribucion - Art. 45 y 46', 'Los pisos, paredes y cielo raso se mantienen en buen estado de conservacion e higiene', 1, 'N', 3);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Mantenimiento de alimentos calientes - Art. 47', 'Los equipos utilizados para mantener alimentos calientes alcanzan una temperatura mayor o igual a 60 C', 2, 'N', 4);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Mantenimiento de alimentos calientes - Art. 47', 'Si cuenta con servicio tipo buffet cada recipiente con comida cuenta con su propio utensilio para servir', 2, 'N', 5);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Mantenimiento de alimentos calientes - Art. 47', 'Las urnas o exhibidores de alimentos como pollo frito, rostizado o carnes preparadas cuentan con bombillos o reflectores protegidos y alcanzan la temperatura de 60 C', 2, 'N', 6);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Mantenimiento de alimentos calientes - Art. 47', 'Las vitrinas refrigeradas para exhibicion de alimentos preparados se mantienen en buen estado de funcionamiento, conservacion e higiene.', 2, 'N', 7);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Mantenimiento de alimentos calientes - Art. 47', 'Las vitrinas no refrigeradas para exhibicion de alimentos se mantienen en buen estado de funcionamiento, conservacion e higiene.', 1, 'N', 8);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Mantenimiento de alimentos calientes - Art. 47', 'Vajilla desechable Cuando se utilicen utensilios de material desechable se descartan, no se permite el reuso.', 1, 'N', 9);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Dispensadores - Art. 51', 'Los recipientes dispensadores de salsas, aderezos, mayonesas, azucar u otros se mantienen rotulados y en buen estado de conservacion e higiene y cerrados.', 1, 'N', 10);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Dispensadores - Art. 51', 'Se mantienen en refrigeracion segun la naturaleza de su contenido.', 2, 'N', 11);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Servicio de comidas - Art. 52', 'La vajilla, cubiertos y vasos se encuentran limpios, secos y en buen estado de conservacion e higiene', 1, 'N', 12);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Servicio de comidas - Art. 52', 'Los operarios manipulan los utensilios correctamente a la hora de servir los alimentos', 1, 'N', 13);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Hielo - Art. 53', 'El hielo para consumo se elabora a partir de agua potable o proviene de una fabrica autorizada por el MS', 2, 'N', 14);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Hielo - Art. 53', 'El hielo se manipula con pinzas y los recipientes se mantienen en buen estado e higiene.', 1, 'N', 15);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'F'), 'Hielo - Art. 53', 'El hielo utilizado para enfriamiento de bebidas o copas no se usa para consumo humano.', 1, 'N', 16);

-- Seccion G
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'G'), 'Transporte para servicio a domicilio - Art. 56', 'Se utilizan envases desechables de primer uso para entregar los alimentos al cliente', 1, 'N', 1);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'G'), 'Transporte para servicio a domicilio - Art. 56', 'Salsas y aderezos debidamente empacados', 1, 'N', 2);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'G'), 'Transporte para servicio a domicilio - Art. 56', 'Los contenedores termicos del vehiculo cuenta con cierre hermetico y seguro', 1, 'N', 3);

-- Seccion H
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'H'), 'Transporte para servicio de catering - Art. 55', 'Vehiculos que transportan alimentos se mantienen en buenas condiciones de higiene', 1, 'N', 1);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'H'), 'Transporte para servicio de catering - Art. 55', 'Cuentan con carroceria cerrada de forma que impidan el ingreso de contaminantes externos', 1, 'N', 2);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'H'), 'Transporte para servicio de catering - Art. 55', 'Los contenedores termicos destinados al transporte de alimentos calientes los mantienen a 60C', 2, 'N', 3);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'H'), 'Transporte para servicio de catering - Art. 55', 'Los recipientes utilizados que tengan contacto directo con los alimentos deben ser de materiales resistentes, de facil limpieza y desinfeccion y no transmitir sustancias toxicas, olores o sabores a los mismos.', 1, 'N', 4);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'H'), 'Transporte para servicio de catering - Art. 55', 'Los alimentos frios se mantienen a temperatura igual o inferior a 5C', 2, 'N', 5);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'H'), 'Transporte para servicio de catering - Art. 55', 'Los utensilios y manteleria se transportan debidamente protegidos de posibles contaminantes.', 1, 'N', 6);

COMMIT;

-- ============================================
-- Verificacion (correr aparte, con Ctrl+Enter)
-- ============================================

-- Tipos de establecimiento y su puntaje maximo:
-- SELECT * FROM INS_TIPO_ESTABLECIMIENTO ORDER BY ORDEN;

-- Secciones que le aplican a 'Ventana' (para pintar el frontend):
-- SELECT s.CODIGO, s.NOMBRE
-- FROM INS_TIPO_SECCION ts
-- JOIN INS_SECCION s ON s.ID_SECCION = ts.ID_SECCION
-- JOIN INS_TIPO_ESTABLECIMIENTO te ON te.ID_TIPO_ESTABLECIMIENTO = ts.ID_TIPO_ESTABLECIMIENTO
-- WHERE te.NOMBRE = 'Ventana'
-- ORDER BY s.ORDEN;

-- Todos los items de una seccion, para pintar el formulario:
-- SELECT s.CODIGO, i.ARTICULO, i.DESCRIPCION, i.PUNTAJE, i.ES_CRITICO, i.ORDEN
-- FROM INS_ITEM i JOIN INS_SECCION s ON s.ID_SECCION = i.ID_SECCION
-- WHERE s.CODIGO = 'B2'
-- ORDER BY i.ORDEN;

-- Total de items por seccion (debe dar 156 en total):
-- SELECT s.CODIGO, COUNT(*) FROM INS_ITEM i JOIN INS_SECCION s ON s.ID_SECCION = i.ID_SECCION GROUP BY s.CODIGO ORDER BY s.CODIGO;
