-- ============================================================
-- SGGDIS - Script de creacion de base de datos (Oracle)
-- Catalogo (Guia, Tipos de establecimiento, Secciones, Items)
-- + Transaccional (Inspecciones)
-- Carga inicial: Seccion A completa (22 items reales)
-- ============================================================

-- ============================================
-- 1. Catalogo: Guia (el reglamento en si)
-- ============================================

CREATE TABLE INS_GUIA (
  ID_GUIA     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  NOMBRE      VARCHAR2(150) NOT NULL,
  DESCRIPCION VARCHAR2(300),
  CATEGORIA   VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_GUIA PRIMARY KEY (ID_GUIA)
);

-- ============================================
-- 2. Catalogo: Tipos de establecimiento (dato real, Excel fila 11-16)
-- ============================================

CREATE TABLE INS_TIPO_ESTABLECIMIENTO (
  ID_TIPO_ESTABLECIMIENTO  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  ID_GUIA                  NUMBER NOT NULL,
  NOMBRE                   VARCHAR2(100) NOT NULL,
  PUNTAJE_MAXIMO           NUMBER NOT NULL,
  ORDEN                    NUMBER NOT NULL,
  CONSTRAINT PK_TIPO_ESTABLECIMIENTO PRIMARY KEY (ID_TIPO_ESTABLECIMIENTO),
  CONSTRAINT FK_TIPOESTABL_GUIA FOREIGN KEY (ID_GUIA) REFERENCES INS_GUIA (ID_GUIA)
);

-- ============================================
-- 3. Catalogo: Secciones de la guia
-- ============================================

CREATE TABLE INS_SECCION (
  ID_SECCION  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  ID_GUIA     NUMBER NOT NULL,
  CODIGO      VARCHAR2(5) NOT NULL,
  NOMBRE      VARCHAR2(150) NOT NULL,
  ORDEN       NUMBER NOT NULL,
  CONSTRAINT PK_SECCION PRIMARY KEY (ID_SECCION),
  CONSTRAINT FK_SECCION_GUIA FOREIGN KEY (ID_GUIA) REFERENCES INS_GUIA (ID_GUIA)
);

-- ============================================
-- 4. Puente: que secciones aplican a cada tipo de establecimiento
-- ============================================

CREATE TABLE INS_TIPO_SECCION (
  ID_TIPO_ESTABLECIMIENTO  NUMBER NOT NULL,
  ID_SECCION               NUMBER NOT NULL,
  CONSTRAINT PK_TIPO_SECCION PRIMARY KEY (ID_TIPO_ESTABLECIMIENTO, ID_SECCION),
  CONSTRAINT FK_TIPOSECCION_TIPO FOREIGN KEY (ID_TIPO_ESTABLECIMIENTO) REFERENCES INS_TIPO_ESTABLECIMIENTO (ID_TIPO_ESTABLECIMIENTO),
  CONSTRAINT FK_TIPOSECCION_SECCION FOREIGN KEY (ID_SECCION) REFERENCES INS_SECCION (ID_SECCION)
);

-- ============================================
-- 5. Catalogo: Items de cada seccion
-- ============================================

CREATE TABLE INS_ITEM (
  ID_ITEM             NUMBER GENERATED BY DEFAULT AS IDENTITY,
  ID_SECCION          NUMBER NOT NULL,
  ARTICULO            VARCHAR2(60) NOT NULL,
  DESCRIPCION         VARCHAR2(400) NOT NULL,
  PUNTAJE             NUMBER NOT NULL,
  ES_CRITICO          CHAR(1) DEFAULT 'N' NOT NULL,
  PERMITE_NO_APLICA   CHAR(1) DEFAULT 'S' NOT NULL,
  ORDEN               NUMBER NOT NULL,
  CONSTRAINT PK_ITEM PRIMARY KEY (ID_ITEM),
  CONSTRAINT FK_ITEM_SECCION FOREIGN KEY (ID_SECCION) REFERENCES INS_SECCION (ID_SECCION),
  CONSTRAINT CK_ITEM_CRITICO CHECK (ES_CRITICO IN ('S','N')),
  CONSTRAINT CK_ITEM_NOAPLICA CHECK (PERMITE_NO_APLICA IN ('S','N'))
);

-- ============================================
-- 6. Transaccional: cada inspeccion real
-- ============================================

CREATE TABLE INS_INSPECCION (
  ID_INSPECCION            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  ID_GUIA                  NUMBER NOT NULL,
  ID_TIPO_ESTABLECIMIENTO  NUMBER NOT NULL,
  FECHA                    DATE NOT NULL,
  CONSECUTIVO              VARCHAR2(30) NOT NULL,
  NOMBRE_ESTABLECIMIENTO   VARCHAR2(200) NOT NULL,
  FECHA_CREACION           DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_INSPECCION PRIMARY KEY (ID_INSPECCION),
  CONSTRAINT FK_INSPECCION_GUIA FOREIGN KEY (ID_GUIA) REFERENCES INS_GUIA (ID_GUIA),
  CONSTRAINT FK_INSPECCION_TIPO FOREIGN KEY (ID_TIPO_ESTABLECIMIENTO) REFERENCES INS_TIPO_ESTABLECIMIENTO (ID_TIPO_ESTABLECIMIENTO),
  CONSTRAINT UQ_INSPECCION_CONSECUTIVO UNIQUE (CONSECUTIVO)
);

-- ============================================
-- 7. Transaccional: respuestas de items en inspecciones
-- ============================================

CREATE TABLE INS_RESPUESTA (
  ID_RESPUESTA               NUMBER GENERATED BY DEFAULT AS IDENTITY,
  ID_INSPECCION              NUMBER NOT NULL,
  ID_ITEM                    NUMBER NOT NULL,
  ESTADO                     VARCHAR2(20) NOT NULL,
  PUNTAJE_OBTENIDO           NUMBER(6,2) DEFAULT 0 NOT NULL,
  OBSERVACION                VARCHAR2(300),
  FECHA_MODIFICACION         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_RESPUESTA PRIMARY KEY (ID_RESPUESTA),
  CONSTRAINT FK_RESPUESTA_INSPECCION FOREIGN KEY (ID_INSPECCION) REFERENCES INS_INSPECCION (ID_INSPECCION),
  CONSTRAINT FK_RESPUESTA_ITEM FOREIGN KEY (ID_ITEM) REFERENCES INS_ITEM (ID_ITEM),
  CONSTRAINT UQ_RESPUESTA_ITEM UNIQUE (ID_INSPECCION, ID_ITEM),
  CONSTRAINT CK_RESPUESTA_ESTADO CHECK (ESTADO IN ('Cumple', 'No cumple', 'No aplica')),
  CONSTRAINT CK_RESPUESTA_PUNTAJE CHECK (PUNTAJE_OBTENIDO >= 0)
);

-- ============================================
-- 7. Datos: Guia
-- ============================================

INSERT INTO INS_GUIA (NOMBRE, DESCRIPCION, CATEGORIA) VALUES
('Guia de Inspeccion para Servicios de Alimentacion al Publico',
 'Reglamento de Servicio de Alimentacion al Publico N 37308-S, Acuerdo 1803',
 'Servicios de Alimentacion al Publico');

-- ============================================
-- 8. Datos: Tipos de establecimiento (reales, Excel)
-- ============================================

INSERT INTO INS_TIPO_ESTABLECIMIENTO (ID_GUIA, NOMBRE, PUNTAJE_MAXIMO, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'), 'Soda, Restaurante o Bar con servicio Express', 210, 1);
INSERT INTO INS_TIPO_ESTABLECIMIENTO (ID_GUIA, NOMBRE, PUNTAJE_MAXIMO, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'), 'Soda, Restaurante o Bar sin servicio Express', 199, 2);
INSERT INTO INS_TIPO_ESTABLECIMIENTO (ID_GUIA, NOMBRE, PUNTAJE_MAXIMO, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'), 'Servicios de Catering', 171, 3);
INSERT INTO INS_TIPO_ESTABLECIMIENTO (ID_GUIA, NOMBRE, PUNTAJE_MAXIMO, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'), 'Servicio Express', 180, 4);
INSERT INTO INS_TIPO_ESTABLECIMIENTO (ID_GUIA, NOMBRE, PUNTAJE_MAXIMO, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'), 'Ventana', 177, 5);

-- ============================================
-- 9. Datos: Seccion A
-- ============================================

INSERT INTO INS_SECCION (ID_GUIA, CODIGO, NOMBRE, ORDEN) VALUES
((SELECT ID_GUIA FROM INS_GUIA WHERE NOMBRE = 'Guia de Inspeccion para Servicios de Alimentacion al Publico'),
 'A', 'Condiciones Fisicas y Sanitarias Generales de las Instalaciones', 1);

-- ============================================
-- 10. Datos: que tipos usan la Seccion A (los 5, segun el Excel)
-- ============================================

INSERT INTO INS_TIPO_SECCION (ID_TIPO_ESTABLECIMIENTO, ID_SECCION)
SELECT ID_TIPO_ESTABLECIMIENTO, (SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A')
FROM INS_TIPO_ESTABLECIMIENTO;

-- ============================================
-- 11. Datos: los 22 items reales de la Seccion A
-- ============================================

INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Ubicacion - Art. 5', 'Distancia mayor o igual a 3m de expendios y bodegas de agroquimicos que no realizan mezclas y mayor o igual a 10m de aquellas que realizan mezclas.', 1, 'N', 1);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Ubicacion - Art. 5', 'Limpios, libres de basura o equipo en desuso', 1, 'N', 2);

INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Alrededores - Art. 6', 'Libres de aguas estancadas', 1, 'N', 3);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Alrededores - Art. 6', 'Zonas verdes y ornamentales recortadas y libres de maleza', 1, 'N', 4);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Alrededores - Art. 6', 'Se observan equipos o materiales en desuso que puedan constituirse en atraccion y refugio para insectos y roedores', 1, 'N', 5);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Alrededores - Art. 6', 'Mantenimiento adecuado de los conductos o canales exteriores que drenan las aguas, para evitar su estancamiento.', 1, 'N', 6);

INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Edificaciones - Art. 7', 'La edificacion se encuentra en buenas condiciones fisicas e higienicas.', 1, 'N', 7);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Edificaciones - Art. 7', 'Cumple con las condiciones de acceso reguladas por la Ley 7600', 1, 'N', 8);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Edificaciones - Art. 7', 'Esta independiente de viviendas u otras actividades de naturaleza distinta', 1, 'N', 9);

INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Distribucion de las Areas - Art. 8 y 9', 'Segun corresponda, cuenta con las areas claramente definidas de: almacenamiento y conservacion, Preparacion, Consumo, Servicios sanitarios', 1, 'N', 10);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Distribucion de las Areas - Art. 8 y 9', 'Las dimensiones permiten el desarrollo adecuado de cada actividad', 1, 'N', 11);

INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones de Gas - Art. 11', 'Las tuberias o mangueras de gas se encuentran en buenas condiciones de funcionamiento (sin fugas)', 2, 'N', 12);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones de Gas - Art. 11', 'Los cilindros se encuentran en buenas condiciones fisicas y sus llaves de salida operan correctamente', 2, 'N', 13);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones de Gas - Art. 11', 'Los cilindros se encuentran en un area ventilada, segura y debidamente protegida, fuera del area preparacion de alimentos.', 2, 'N', 14);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones de Gas - Art. 11', 'Cuentan con una bitacora donde se anota el mantenimiento preventivo y correctivo de las instalaciones de gas.', 2, 'N', 15);

INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Abastecimiento de Agua Potable - Art. 10', 'Disposicion de agua potable siempre', 3, 'S', 16);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Abastecimiento de Agua Potable - Art. 10', 'Agua suficiente para ejecutar todas las operaciones en el establecimiento', 3, 'S', 17);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Abastecimiento de Agua Potable - Art. 10', 'Existe un procedimiento escrito para la higienizacion de tanques de almacenamiento cuando cuenten con estos.', 2, 'S', 18);

INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones Electricas - Art. 12', 'El cableado electrico, tomacorrientes, interruptores y enchufes se mantiene en buenas condiciones de funcionamiento.', 2, 'N', 19);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones Electricas - Art. 12', 'Cuenta con caja de Brecker en buen estado de funcionamiento', 1, 'N', 20);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones Electricas - Art. 12', 'El cableado electrico se encuentra entubado', 1, 'N', 21);
INSERT INTO INS_ITEM (ID_SECCION, ARTICULO, DESCRIPCION, PUNTAJE, ES_CRITICO, ORDEN) VALUES
((SELECT ID_SECCION FROM INS_SECCION WHERE CODIGO = 'A'), 'Instalaciones Electricas - Art. 12', 'Tomacorrientes e interruptores se encuentran anclados.', 1, 'N', 22);

COMMIT;

-- ============================================
-- Verificacion (correr aparte, con Ctrl+Enter)
-- ============================================

-- SELECT * FROM INS_TIPO_ESTABLECIMIENTO ORDER BY ORDEN;
--
-- SELECT s.CODIGO, i.ARTICULO, i.DESCRIPCION, i.PUNTAJE, i.ES_CRITICO
-- FROM INS_ITEM i JOIN INS_SECCION s ON s.ID_SECCION = i.ID_SECCION
-- ORDER BY i.ORDEN;
