export const REGIONES_SALUD = [
  {
    codigo: 'HN',
    nombre: 'Huetar Norte',
    areas: [
      { codigo: 'F', nombre: 'Florencia' },
      { codigo: 'SRP', nombre: 'Santa Rosa Pocosol' },
      { codigo: 'LC', nombre: 'Los Chiles' },
      { codigo: 'AZ', nombre: 'Aguas Zarcas' },
      { codigo: 'CQ', nombre: 'Ciudad Quesada' },
      { codigo: 'G', nombre: 'Guatuso' },
    ],
  },
  {
    codigo: 'CH',
    nombre: 'Chorotega',
    areas: [
      { codigo: 'AB', nombre: 'Abangares' },
      { codigo: 'B', nombre: 'Bagaces' },
      { codigo: 'CA', nombre: 'Cañas' },
      { codigo: 'CR', nombre: 'Carrillo' },
      { codigo: 'HJ', nombre: 'Hojancha' },
      { codigo: 'LC', nombre: 'La Cruz' },
      { codigo: 'L', nombre: 'Liberia' },
      { codigo: 'N', nombre: 'Nandayure' },
      { codigo: 'U', nombre: 'Upala' },
      { codigo: 'T', nombre: 'Tilarán' },
      { codigo: 'NI', nombre: 'Nicoya' },
      { codigo: 'SC', nombre: 'Santa Cruz' },
    ],
  },
  {
    codigo: 'CS',
    nombre: 'Central Sur',
    areas: [
      { codigo: 'AC', nombre: 'Acosta' },
      { codigo: 'AL', nombre: 'Alajuelita' },
      { codigo: 'AS', nombre: 'Aserrí' },
      { codigo: 'CO', nombre: 'Coronado' },
      { codigo: 'CU', nombre: 'Curridabat' },
      { codigo: 'D', nombre: 'Desamparados' },
      { codigo: 'C-M-U', nombre: 'Carmen-Merced-Uruca' },
      { codigo: 'E', nombre: 'Escazú' },
      { codigo: 'G', nombre: 'Goicoechea' },
      { codigo: 'H', nombre: 'Hatillo' },
      { codigo: 'H-MR', nombre: 'Hospital-Mata Redonda' },
      { codigo: 'MDO', nombre: 'Montes de Oca' },
      { codigo: 'SA', nombre: 'Santa Ana' },
      { codigo: 'SM', nombre: 'Sureste Metropolitana' },
      { codigo: 'T', nombre: 'Tibás' },
      { codigo: 'M', nombre: 'Moravia' },
      { codigo: 'P', nombre: 'Pavas' },
    ],
  },
  {
    codigo: 'CO',
    nombre: 'Central Occidente',
    areas: [
      { codigo: 'SR', nombre: 'San Ramón' },
      { codigo: 'P', nombre: 'Palmares' },
      { codigo: 'N', nombre: 'Naranjo' },
      { codigo: 'S', nombre: 'Sarchí' },
      { codigo: 'Z', nombre: 'Zarcero' },
    ],
  },
  {
    codigo: 'CN',
    nombre: 'Central Norte',
    areas: [
      { codigo: 'A1', nombre: 'Alajuela 1' },
      { codigo: 'A2', nombre: 'Alajuela 2' },
      { codigo: 'AT', nombre: 'Atenas' },
      { codigo: 'B-F', nombre: 'Belén-Flores' },
      { codigo: 'G', nombre: 'Grecia' },
      { codigo: 'H', nombre: 'Heredia' },
      { codigo: 'P', nombre: 'Poás' },
      { codigo: 'SP-SI', nombre: 'San Pablo-San Isidro' },
      { codigo: 'SR', nombre: 'San Rafael' },
      { codigo: 'SB', nombre: 'Santa Bárbara' },
      { codigo: 'SD', nombre: 'Santo Domingo' },
      { codigo: 'S', nombre: 'Sarapiquí' },
    ],
  },
  {
    codigo: 'BR',
    nombre: 'Brunca',
    areas: [
      { codigo: 'PZ', nombre: 'Pérez Zeledón' },
      { codigo: 'BA', nombre: 'Buenos Aires' },
      { codigo: 'C', nombre: 'Coto' },
      { codigo: 'CO', nombre: 'Corredores' },
      { codigo: 'G', nombre: 'Golfito' },
      { codigo: 'CB', nombre: 'Coto Brus' },
    ],
  },
  {
    codigo: 'CE',
    nombre: 'Central Este',
    areas: [
      { codigo: 'C', nombre: 'Cartago' },
      { codigo: 'LU', nombre: 'La Unión' },
      { codigo: 'LS', nombre: 'Los Santos' },
      { codigo: 'O', nombre: 'Oreamuno' },
      { codigo: 'P', nombre: 'Paraíso' },
      { codigo: 'T', nombre: 'Turrialba' },
      { codigo: 'EG', nombre: 'El Guarco' },
    ],
  },
  {
    codigo: 'HC',
    nombre: 'Huetar Caribe',
    areas: [
      { codigo: 'T', nombre: 'Talamanca' },
      { codigo: 'L', nombre: 'Limón' },
      { codigo: 'M', nombre: 'Matina' },
      { codigo: 'P', nombre: 'Pococí' },
      { codigo: 'S', nombre: 'Siquirres' },
      { codigo: 'G', nombre: 'Guácimo' },
    ],
  },
  {
    codigo: 'PC',
    nombre: 'Pacífico Central',
    areas: [
      { codigo: 'A', nombre: 'Aguirre' },
      { codigo: 'B', nombre: 'Barranca' },
      { codigo: 'E', nombre: 'Esparza' },
      { codigo: 'MO', nombre: 'Montes de Oro' },
      { codigo: 'O-SM', nombre: 'Orotina-San Mateo' },
      { codigo: 'P', nombre: 'Parrita' },
      { codigo: 'G', nombre: 'Garabito' },
      { codigo: 'P-CH', nombre: 'Puntarenas-Chacarita' },
    ],
  },
];